Eric/detect vue
oslabs-beta/Vueable-query pull request #11
Opened 2023-05-22 19:11 UTC by ectjon

Add ability for script.js to find vue apps not mounted on a #app element.
Catch errors when Vue and Tanstack query aren't running on the page and console.log them

2023-05-22 20:46 UTC, eswitbeck requested changes
Nice and straightforward! I'm thinking we should make a point to add a conditional display (presumably with another message and state) to the devtool to make this all doubly obvious, simply displaying the logged text.

A very small request: could you please include the semicolons starting at line 88 for consistency?

2023-05-22 21:49 UTC, ectjon commented
I changed the console logs to console errors, but they show up under errors in the extension tab. 
Since it's expected to not detect Vue on many pages, do you think it'd make sense to throw an error? 

I do like the idea about displaying a descriptive error message in the Devtool panel though, I can try to add some more changes.
<img width="422" alt="Screenshot 2023-05-22 at 2 47 11 PM" src="https://github.com/oslabs-beta/Vueable-query/assets/44622893/604372c2-8fe7-4449-951c-b11190df92b0">

2023-05-22 22:15 UTC, eswitbeck approved these changes
Very good point; it probably makes sense for things to fail silently and fit most of our description into the panel. Looks good to go--thanks!

2023-05-25 17:20 UTC, annaduong94 approved these changes

2023-05-25 17:20 UTC, merged